hunter_config(Boost VERSION ${HUNTER_Boost_VERSION}
    CMAKE_ARGS 
        BUILD_SHARED_LIBS=ON 
        Boost_USE_STATIC_LIBS=OFF
        Boost_USE_MULTITHREADED=ON
        Boost_USE_STATIC_RUNTIME=OFF
        BOOST_ALL_DYN_LINK=ON
)

if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
hunter_config(glm VERSION ${HUNTER_glm_VERSION}
    CMAKE_ARGS 
        GLM_FORCE_CTOR_INIT=ON
)
endif()

hunter_config(imgui VERSION ${HUNTER_imgui_VERSION}
    CMAKE_ARGS 
        IMGUI_BUILD_EXAMPLES=OFF
        IMGUI_ENABLE_TEST_ENGINE=OFF
        IMGUI_IMPL_OPENGL3=ON
        IMGUI_IMPL_GLFW=ON
        IMGUI_IMPL_OPENGL_LOADER=GLEW
)

hunter_config(HastyNoise VERSION ${HUNTER_HastyNoise_VERSION}
    CMAKE_ARGS 
        HN_PREVIEW_APP=OFF
        HN_BUILD_APP=OFF
)
